spring.application.name=EjercicioPractico2_SantiagoJimenezCECI



server.port=78

spring.datasource.url=jdbc:mysql://localhost:3306/medicare?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123451

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
#CONFIGURAR DEPENDE EL CORREO DESDE EL QUE SE QUIERA ENVIAR 
spring.mail.username=santiagojimenezceci@gmail.com
spring.mail.password=fakepassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
