spring.application.name=EjercicioPractico2_SantiagoJimenezCECI



server.port=78

spring.datasource.url=jdbc:mysql://localhost:3306/medicare?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123451

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
